--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SilverzPlayz/SilverzEssentials
branches:
- master
projects:
  SilverzEssentials:
    path: ""
    icon: "icons8-new-message-64.png"
...
