name: SilverzEssentials
api: [3.0.0]
main: SilverzPlayz\SilverzEssentials\Main
version: 1.0
commands:
  broadcast:
    description: "Broadcast a Message"
    aliases: ["bcast", "bc"]
permissions:
  broadcast.cmd.bcast:
    default: op
  
